# Generated by Django 5.1.6 on 2025-02-11 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolbackend', '0002_student_other_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='surname',
        ),
    ]
