# Generated by Django 5.1.6 on 2025-02-11 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolbackend', '0005_alter_courseenrollment_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourses',
            name='unique_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='schoolbackend.userfaculty'),
        ),
    ]
